# Автоматическая сборка exe-файла при создании релиза
# Этот файл нужно положить в папку .github/workflows/

name: Build Windows EXE

# Когда запускать сборку:
on:
  # При пуше тега с версией (например v1.0.0)
  push:
    tags:
      - 'v*'
  # Также можно запустить вручную
  workflow_dispatch:

jobs:
  build:
    # Используем виртуальную машину Windows
    runs-on: windows-latest
    
    steps:
    # Шаг 1: Скачиваем код из репозитория
    - name: Checkout code
      uses: actions/checkout@v4
    
    # Шаг 2: Настраиваем MSVC (компилятор от Microsoft)
    - name: Setup MSVC
      uses: microsoft/setup-msbuild@v2
    
    # Шаг 3: Компилируем программу
    - name: Compile with MSVC
      shell: cmd
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        cl /EHsc /O2 /Fe:StudentGrades.exe main.cpp
    
    # Шаг 4: Загружаем exe как артефакт (можно скачать)
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: StudentGrades-Windows
        path: StudentGrades.exe
    
    # Шаг 5: Создаем релиз и прикрепляем exe
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: StudentGrades.exe
        name: "Система учета студентов ${{ github.ref_name }}"
        body: |
          ## Скачать
          
          Скачайте файл `StudentGrades.exe` ниже.
          
          ## Запуск
          
          1. Скачайте файл
          2. Запустите StudentGrades.exe
          3. Готово!
          
          ## Примечание
          
          Для корректного отображения русского языка убедитесь, 
          что в терминале установлена кодировка UTF-8.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
